# Generated by Django 5.2.7 on 2026-09-17 15:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="media/project_images/",
                verbose_name="تصویر",
            ),
        ),
    ]
