# Generated by Django 5.2.4 on 2025-07-23 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان')),
                ('excerpt', models.TextField(blank=True, max_length=500, verbose_name='خلاصه')),
                ('content', models.TextField(verbose_name='محتوا')),
                ('image', models.ImageField(blank=True, null=True, upload_to='blog_images/', verbose_name='تصویر')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ به\u200cروزرسانی')),
                ('is_published', models.BooleanField(default=False, verbose_name='منتشر شده')),
            ],
            options={
                'verbose_name': 'پست',
                'verbose_name_plural': 'پست\u200cها',
                'ordering': ['-created_at'],
            },
        ),
    ]
