# Generated by Django 5.2.7 on 2026-09-17 16:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0003_alter_post_options_post_pdf_alter_post_content_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="is_pinned",
            field=models.BooleanField(
                default=False,
                help_text="Pinned published posts appear on the main page.",
                verbose_name="Pin to homepage",
            ),
        ),
    ]
