# Generated by Django 5.2.7 on 2026-09-17 15:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0002_teammember"),
    ]

    operations = [
        migrations.AddField(
            model_name="sitesettings",
            name="map_embed_url",
            field=models.URLField(
                blank=True,
                default="https://www.google.com/maps?q=Kupandole,+Lalitpur,+Nepal&output=embed",
                help_text="Google Maps embed URL for the contact page. In Google Maps: Share the place → Embed a map → copy the src URL.",
            ),
        ),
    ]
