# Generated by Django 5.2.7 on 2026-09-17 15:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0005_notice_sitesettings_show_blog_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="SocialLink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "platform",
                    models.CharField(
                        choices=[
                            ("facebook", "Facebook"),
                            ("instagram", "Instagram"),
                            ("linkedin", "LinkedIn"),
                            ("x", "X (Twitter)"),
                            ("youtube", "YouTube"),
                            ("tiktok", "TikTok"),
                            ("whatsapp", "WhatsApp"),
                            ("viber", "Viber"),
                            ("other", "Other / Website"),
                        ],
                        default="facebook",
                        max_length=20,
                        verbose_name="Platform",
                    ),
                ),
                (
                    "label",
                    models.CharField(
                        blank=True,
                        help_text="Optional. Overrides the platform name (useful for 'Other / Website').",
                        max_length=100,
                        verbose_name="Custom label",
                    ),
                ),
                ("url", models.URLField(verbose_name="Link")),
                ("order", models.PositiveIntegerField(default=0, verbose_name="Order")),
                ("is_active", models.BooleanField(default=True, verbose_name="Active")),
            ],
            options={
                "verbose_name": "Social link",
                "verbose_name_plural": "Social links",
                "ordering": ["order", "id"],
            },
        ),
    ]
