# Generated by Django 5.2.7 on 2026-09-17 15:23

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SiteSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "company_name",
                    models.CharField(default="Pivot Risk Pvt. Ltd.", max_length=200),
                ),
                (
                    "tagline",
                    models.CharField(
                        default="RISK MANAGEMENT & ADVISORY", max_length=200
                    ),
                ),
                (
                    "logo",
                    models.ImageField(blank=True, null=True, upload_to="media/site/"),
                ),
                (
                    "accent_color",
                    models.CharField(
                        default="#c72f2b",
                        help_text="Primary accent color (hex, e.g. #c72f2b)",
                        max_length=7,
                    ),
                ),
                (
                    "deep_color",
                    models.CharField(
                        default="#163d7f",
                        help_text="Deep blue for headings & logo (hex, e.g. #163d7f)",
                        max_length=7,
                    ),
                ),
                (
                    "ink_color",
                    models.CharField(
                        default="#0d2349",
                        help_text="Dark ink used for text & footer (hex, e.g. #0d2349)",
                        max_length=7,
                    ),
                ),
                (
                    "paper_color",
                    models.CharField(
                        default="#f4f7fb",
                        help_text="Page background (hex, e.g. #f4f7fb)",
                        max_length=7,
                    ),
                ),
                (
                    "address",
                    models.CharField(
                        default="Kupandole, Lalitpur, Nepal", max_length=255
                    ),
                ),
                (
                    "email",
                    models.EmailField(default="hello@pivotrisk.com.np", max_length=254),
                ),
                ("phone", models.CharField(default="+977 1-000-0000", max_length=50)),
                (
                    "hours",
                    models.CharField(
                        default="Sunday – Friday, 10:00 – 17:00", max_length=120
                    ),
                ),
                (
                    "footer_blurb",
                    models.TextField(
                        default="Risk management and advisory, based in Kupandole, Lalitpur. Working with organizations across Nepal.",
                        help_text="Short description shown in the site footer.",
                    ),
                ),
                (
                    "copyright_name",
                    models.CharField(
                        default="Pivot Risk Pvt. Ltd.",
                        help_text="Name shown in the footer copyright line.",
                        max_length=200,
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Site settings",
                "verbose_name_plural": "Site settings",
            },
        ),
    ]
