# Generated by Django 5.2.7 on 2026-09-17 15:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="TeamMember",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="Name")),
                (
                    "role",
                    models.CharField(blank=True, max_length=200, verbose_name="Role"),
                ),
                ("bio", models.TextField(blank=True, verbose_name="Short bio")),
                (
                    "photo",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="media/team_photos/",
                        verbose_name="Photo",
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0, verbose_name="Order")),
                ("is_active", models.BooleanField(default=True, verbose_name="Active")),
            ],
            options={
                "verbose_name": "Team member",
                "verbose_name_plural": "Team members",
                "ordering": ["order", "id"],
            },
        ),
    ]
