# Generated by Django 5.2.7 on 2026-09-17 15:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0003_sitesettings_map_embed_url"),
    ]

    operations = [
        migrations.CreateModel(
            name="ContactMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="Name")),
                ("email", models.EmailField(max_length=254, verbose_name="Email")),
                (
                    "organization",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Organization"
                    ),
                ),
                ("message", models.TextField(verbose_name="Message")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("taken", "Action taken"),
                            ("not_taken", "Not taken"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Received at"),
                ),
            ],
            options={
                "verbose_name": "Contact message",
                "verbose_name_plural": "Contact messages",
                "ordering": ["-created_at"],
            },
        ),
    ]
