# Generated by Django 5.2.7 on 2026-09-17 15:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0004_contactmessage"),
    ]

    operations = [
        migrations.CreateModel(
            name="Notice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="Title")),
                ("body", models.TextField(blank=True, verbose_name="Details")),
                (
                    "attachment",
                    models.FileField(
                        blank=True,
                        help_text="Optional. Upload a PDF or an image.",
                        null=True,
                        upload_to="media/notices/",
                        verbose_name="Attachment (PDF or image)",
                    ),
                ),
                (
                    "link",
                    models.URLField(
                        blank=True,
                        help_text="Optional. Opens in a new tab.",
                        verbose_name="External link",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Active")),
                (
                    "is_pinned",
                    models.BooleanField(default=False, verbose_name="Pin to top"),
                ),
                (
                    "published_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Posted at"),
                ),
            ],
            options={
                "verbose_name": "Notice",
                "verbose_name_plural": "Notices",
                "ordering": ["-is_pinned", "-published_at"],
            },
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="show_blog",
            field=models.BooleanField(default=True, verbose_name="Show Blog section"),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="show_contact",
            field=models.BooleanField(
                default=True, verbose_name="Show Contact section"
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="show_notices",
            field=models.BooleanField(
                default=True, verbose_name="Show Notices section"
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="show_projects",
            field=models.BooleanField(
                default=True, verbose_name="Show Projects section"
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="show_services",
            field=models.BooleanField(
                default=True, verbose_name="Show Services section"
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="show_team",
            field=models.BooleanField(default=True, verbose_name="Show Team section"),
        ),
    ]
