# Generated by Django 5.2.7 on 2026-09-17 15:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0006_sociallink"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sociallink",
            name="url",
            field=models.CharField(
                help_text="Full link, e.g. https://facebook.com/yourpage or https://wa.me/9779800000000",
                max_length=500,
                verbose_name="Link",
            ),
        ),
    ]
