# Generated by Django 5.2.7 on 2026-09-17 16:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0007_alter_sociallink_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="notice",
            name="show_as_popup",
            field=models.BooleanField(
                default=True,
                help_text="If on, this notice pops up once per visit (with a preview of the attachment).",
                verbose_name="Show as popup on site load",
            ),
        ),
    ]
